#! /usr/bin/env bash
# Push a single file to the home directory of all users on a tljh instance.

FILE=/etc/skel/hello-$OES_HUB.ipynb

echo "Copying $FILE:"
for _dir in /home/*; do
    /usr/bin/cp "$FILE" $_dir
    echo "-> $_dir"
done

exit 0
